# Utiliser l'image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Mettre à jour la liste des paquets disponibles
RUN apt-get update

# Mettre à jour les paquets installés
RUN apt-get upgrade -y

# Ajouter une commande pour afficher "Hello, World!"
CMD echo "Hello, World!"
